Repository MasterIfeanyi/My-own-quiz-game, pull requests merged in 2022-10, with the labels that each got.

#2 Implemented using React
  quiz/.gitignore
  quiz/package-lock.json
  quiz/package.json
  quiz/public/favicon.ico
  quiz/public/index.html
  quiz/public/logo192.png
  quiz/public/logo512.png
  quiz/public/manifest.json
  quiz/public/robots.txt
  quiz/src/App.css
  quiz/src/App.js
  quiz/src/QuestionComponent.js
  quiz/src/index.css
  quiz/src/index.js
Labels: documentation, help wanted, good first issue, hacktoberfest, hacktoberfest-accepted

#10 added questions
  src/App.js
Labels: documentation, enhancement, help wanted, good first issue, hacktoberfest, hacktoberfest-accepted

#11 added new questions
  src/App.js
Labels: bug, enhancement, hacktoberfest, hacktoberfest-accepted

#14 add netlify redirects
  netlify.toml
Labels: bug, documentation, enhancement, help wanted, good first issue, hacktoberfest, hacktoberfest-accepted

#15 Update App.js
  src/App.js
Labels: documentation, duplicate, enhancement, help wanted, good first issue, hacktoberfest, hacktoberfest-accepted

#17 added restart button to the question component
  src/QuestionComponent.js
Labels: bug, enhancement, question, hacktoberfest, hacktoberfest-accepted
